### ISSUE TITLE
issue with 'align'

### ISSUE THREAD

**Issue by yongshes** [vastgroup/vast-tools#100]
Hi,

I tried to align sequences and got the following error message. I'd appreciate your help.

[vast align]: Input RNA-seq file(s): READ1.fa.gz
Use of uninitialized value $length in concatenation (.) or string at /home/Scripts/vast-tools/bin/RunDBS_1.pl line 489.
Use of uninitialized value $percF in concatenation (.) or string at /home/Scripts/vast-tools/bin/RunDBS_1.pl line 489.
[vast align]: Most common read length detected for fq1:  (%)
[vast align]: Sample name: READ1 
[vast align]: Using VASTDB -> /home/vast-tools/VASTDB/Hsa
[vast align]: Setting output directory to /home/FASTQ/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /home/FASTQ/vast_out/tmp!
Use of uninitialized value $length in subtraction (-) at /home/Scripts/vast-tools/bin/RunDBS_1.pl line 522.
Use of uninitialized value $length in concatenation (.) or string at /home/Scripts/vast-tools/bin/RunDBS_1.pl line 523.
[vast align error]: Trim5 (0) cannot be applied for reads of length 

Use of uninitialized value $length in numeric ge (>=) at /home/Scripts/vast-tools/bin/RunDBS_1.pl line 531.
[vast align error]: Minimum reads length has to be 50nt

**Comment by mirimia** [comment]
Hello,

It's strange; it's not detecting the reads at all. Can you please paste the first few reads of your file? (I'm assuming they are >= 50 in FASTA format?)

Thanks
Manu

**Comment by yongshes** [comment]
Hi Manu,

Thanks for you quick reply. Here is a couple of reads from the fastq file that I am using:

@K00339:125:HWJH7BBXX:1:1101:1529:1578 1:N:0:ATCACG
GGGCGATGCGGCGCGCCTTGGCTTGCCGGGCCTTACGTCTGCGGATCTTACGGGCCGGCTGGTTGAACCACGTGGCCACGCGCCGCTGCCAGTCCTTGTG
+
AAFFFFJJJJJJJAJJFJJJJJJJJJJJJFJJJJJJJJJJJJJJF7F7<JJJFJJJJAFJJJJJFJJJJJJJ<JF<AFJJJJJJJJJJJJJJJJJJJJJJ
@K00339:125:HWJH7BBXX:1:1101:2301:1578 1:N:0:ATCACG
CCCCACAGCAGCCCCTGGAGGTTGTGGTAGGCGGAAAATGCAGAAACTTCTCTCAAAAGCGTCCATGTGGCTCTGTTGGGCCAGGCGGGTAGGGGACTCA
+
AAFFFJJJJJJJJJFJJJJJJAFJJJJJJJJJJJJJJJJJJJJJJJF<JJ<AAJJJJJJJJ<<AFJJ<FJJFF-FAAAFJFJJJFAJJAAJJJJJJJFJJ


It doesn’t have the length information in it. Do you know of any tools that can convert my file to the required format?

Thanks.

**Comment by mirimia** [comment]
OK. I think this is because you're using FASTQ files but your file extension is .fa.gz (for FASTA). If you rename them to .fq.gz or .fastq.gz it should work.

M

**Comment by yongshes** [comment]
Thanks, that solved the problem!

But now I get a new error:

gzip: stdout: Disk quota exceeded
gzip: write error: Disk quota exceeded

There is plenty of disk space on my server. Sorry for bothering you with these small things, but I’d really appreciate your advice.

Thanks again!

**Comment by yongshes** [comment]
By the way, there was one warning message when I ran ./install.R:

Using R version 4.0.4 (2021-02-15)
Looking for VAST Database [VASTDB]
Found 'VASTDB'.. Do you want to download yet uninstalled datasets or update installed datasets? [y/n]: n
Trying to load required package: MASS
Trying to load required package: getopt
Trying to load required package: optparse
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
Trying to load required package: devtools
Warning message:
In for (i in seq_along(cenv$extra)) { : closing unused connection 3 (stdin)
Loading required package: psiplot
Setting vast-tools permissions... success!
/dfs4/som/yongshes/Scripts/bowtie-1.0.0/bowtie
Found bowtie... Everything looks --OK

I am not sure if this warning message is normal. Thanks.

**Comment by mirimia** [comment]
Good. 

Re the new errors, I doubt they are related to vast-tools (?). Ie. It seems a gzip issue somehow, so I have no clue why it could be...

Re the installation warning, we are changing that script, so perhaps is not working well. In any case, this is just to install R libraries and R is not used in align.

**Comment by yongshes** [comment]
OK, thanks again for all your help!
