### ISSUE TITLE
Align issue "Failed in RunDBS_1.pl! at /usr/local/vast-tools/bin/RunDBS_1.pl"

### ISSUE THREAD

**Issue by neusmf** [vastgroup/vast-tools#104]
Hi, 
I am trying to run align but I got an error. I try it using the container and also with the software on the path, and in all cases I had the same problem. I think that is similar to [Issue#67](https://github.com/vastgroup/vast-tools/issues/67).

Here you have the error log:
readline() on closed filehandle VERSION at /usr/local/bin/vast-tools line 65.
Use of uninitialized value $version in scalar chomp at /usr/local/bin/vast-tools line 66.
readline() on closed filehandle VERSION at /usr/local/vast-tools/bin/RunDBS_1.pl line 261.
Use of uninitialized value $version in scalar chomp at /usr/local/vast-tools/bin/RunDBS_1.pl line 262.
[vast align]: VAST-TOOLS vNo version found
[vast align]: Species assembly: hg38, VASTDB Species key: Hs2
[vast align]: VASTDB Version: vastdb.hs2.23.06.20
[vast align]: Input RNA-seq file(s): /fasterqcdump_output/SRR6916959_1.fastq.gz and /fasterqcdump_output/SRR6916959_2.fastq.gz
[vast align]: Most common read lengths detected for fq1 & fq2: 96 (100.00%) and 96 (100.00%)
[vast align]: Sample name: SRR6916959_1 
[vast align]: Using VASTDB -> /01_Vast-tools_C/Hs2
[vast align]: Setting output directory to test
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to 01_Vast-tools_C/test/tmp!
# reads processed: 500000
# reads with at least one reported alignment: 346874 (69.37%)
# reads that failed to align: 138413 (27.68%)
# reads with alignments suppressed due to -m: 14713 (2.94%)
Reported 346874 alignments to 1 output stream(s)
[vast align]:    fraction of first reads mapping to fwd / rev strand : 0.5211 / 0.4789
# reads processed: 500000
# reads with at least one reported alignment: 343039 (68.61%)
# reads that failed to align: 142475 (28.50%)
# reads with alignments suppressed due to -m: 14486 (2.90%)
Reported 343039 alignments to 1 output stream(s)
[vast align]:    fraction of second reads mapping to fwd / rev strand : 0.5161 / 0.4839
[vast align]: Mapping RNAseq reads against mRNA sequences
[vast align]: Calculating cRPKMs
Modification of non-creatable array value attempted, subscript -7 at /usr/local/vast-tools/bin/expr_RPKM.pl line 43, <> line 9494512.
Error while flushing and closing output
terminate called after throwing an instance of 'int'
Aborted (core dumped)
[vast align error]: gzip -dc /fasterqcdump_output/SRR6916959_1.fastq.gz | /usr/local/vast-tools/bin/Trim.pl --once --targetLen 50 -v | bowtie  -q -5 0 -p 8 -m 1 -v 2 01_Vast-tools_C/Hs2/EXPRESSION/mRNA - | /usr/local/vast-tools/bin/expr_RPKM.pl - /01_Vast-tools_C/Hs2/EXPRESSION/Hs2_mRNA-50.eff expr_out/SRR69169
59_1 > expr_out/SRR6916959_1.cRPKM Failed in RunDBS_1.pl! at /usr/local/vast-tools/bin/RunDBS_1.pl line 207.

Thanks in advance,
Neus

**Comment by mirimia** [comment]
Hi Neus,

I think it might be an issue with the folder structure or permissions.

How did you run align? (The full command).

Thanks

**Comment by neusmf** [comment]
Hi,
I used the following command:
vast-tools align --dbDir ./ /fasterqcdump_output/SRR6916959_1.fastq.gz /fasterqcdump_output/SRR6916959_2.fastq.gz -o test -c 8 -sp Hs2

When I run it in the container then I run: "singularity exec ./vast-tools.sif ./align_test.sh", where I have the command above in align_test.sh

Thanks,
Neus

**Comment by mirimia** [comment]
Can you try deleting

--dbDir ./

?

**Comment by neusmf** [comment]
Thanks! This worked!
