### ISSUE TITLE
binom.test error: 'x' must be nonnegative and integer

### ISSUE THREAD

**Issue by ferngonz** [vastgroup/vast-tools#115]
Hello, 
I'm running combine tool, but I get error when using optparse package. I'm running R/4.2.0. 
Also, is this error related to the INCLUSION_LEVELS_ALT3-Mm24-n.tab not being found? 

Thank you for all your help! Below is full output message with error.

[vast combine]: VAST-TOOLS v2.5.1
[vast combine]: Species assembly: mm10, VASTDB Species key: Mm2
[vast combine]: Using VASTDB -> /scratch/users/ferngonz/vast-tools/Mm2
[vast combine]: VASTDB Version: vastdb.mm2.23.06.20
[vast combine]: Building Table for COMBI (splice-site based pipeline)
[vast combine combi]: Loading strand-unspecific mappability for each EEJ and length:
[vast combine combi]: Loading: /scratch/users/ferngonz/vast-tools/Mm2/FILES/Mm2_COMBI-M-50-gDNA.eff     Length: 50
[vast combine combi]: Loading strand-specific mappability for each EEJ and length:
[vast combine combi]: Loading: /scratch/users/ferngonz/vast-tools/Mm2/FILES/Mm2_COMBI-M-50-gDNA-SS.eff  Length: 50
[vast combine combi]: Parsing Template file
[vast combine combi]: Loading EEJ read counts data
[vast combine combi]:    AKO1: found to_combine/AKO1.info. Sample will be treated as being strand-specific.
[vast combine combi]:    AKO2: found to_combine/AKO2.info. Sample will be treated as being strand-specific.
[vast combine combi]:    WT1: found to_combine/WT1.info. Sample will be treated as being strand-specific.
[vast combine combi]:    WT2: found to_combine/WT2.info. Sample will be treated as being strand-specific.
[vast combine combi]: Quantifying PSIs

[vast combine]: Building Table for EXSK (transcript-based pipeline, single)
[vast combine apr]: Loading and parsing data for each sample for EXSK
[vast combine apr]: Parsing info and getting Quality scores (Q) for EXSK

[vast combine]: Building Table for MULTI (transcript-based pipeline, multiexon)
[vast combine apr]: Loading and parsing data for each sample for MULTI
[vast combine apr]: Parsing info and getting Quality scores (Q) for MULTI

[vast combine]: Building Table for MIC (microexon pipeline)

[vast combine]: Building Table for ANNOT (annotation-based pipeline)
[vast combine annot]: Loading strand-unspecific mappability for each EEJ and length:
[vast combine annot]: Loading: /scratch/users/ferngonz/vast-tools/Mm2/FILES/Mm2_COMBI-M-50-gDNA.eff     Length: 50
[vast combine annot]: Loading strand-unspecific mappability for each EEJ and length:
[vast combine annot]: Loading: /scratch/users/ferngonz/vast-tools/Mm2/FILES/Mm2_COMBI-M-50-gDNA-SS.eff  Length: 50
[vast combine annot]: Parsing Template file
[vast combine annot]: Loading EEJ read counts data
[vast combine annot]:    AKO1: found to_combine/AKO1.info. Sample will be treated as being strand-specific.
[vast combine annot]:    AKO2: found to_combine/AKO2.info. Sample will be treated as being strand-specific.
[vast combine annot]:    WT1: found to_combine/WT1.info. Sample will be treated as being strand-specific.
[vast combine annot]:    WT2: found to_combine/WT2.info. Sample will be treated as being strand-specific.
[vast combine annot]: Quantifying PSIs

[vast combine]: Building quality score table for intron retention (version 2)
[vast combine IR]:    AKO1: found to_combine/AKO1.info. Sample will be treated as being strand-specific.
[vast combine IR]:    AKO2: found to_combine/AKO2.info. Sample will be treated as being strand-specific.
Use of uninitialized value $temp[4] in sprintf at /scratch/users/ferngonz/vast-tools/bin/RI_MakeCoverageKey_v2.pl line 110, <IN> line 144190.
Use of uninitialized value $temp[4] in sprintf at /scratch/users/ferngonz/vast-tools/bin/RI_MakeCoverageKey_v2.pl line 110, <IN> line 144190.
[vast combine IR]:    WT1: found to_combine/WT1.info. Sample will be treated as being strand-specific.
[vast combine IR]:    WT2: found to_combine/WT2.info. Sample will be treated as being strand-specific.

[vast combine error]: in call /scratch/users/ferngonz/vast-tools/bin/RI_MakeTablePIR.R --verbose 1 -s /scratch/users/ferngonz/vast-tools/Mm2 --IR_version 2 -c /scratch/users/ferngonz/vast-tools/vast_out/to_combine -q /scratch/users/ferngonz/vast-tools/vast_out/to_combine/Coverage_key_v2-Mm24.IRQ -o /scratch/users/ferngonz/vast-tools/vast_out/raw_incl
Trying to load required package: optparse
Merging IR of 4 sample(s)...
AKO1 
AKO2 
Error in binom.test(x = x[1], n = x[2], p = 1/3.5, alternative = "less") : 
  'x' must be nonnegative and integer
Calls: apply -> FUN -> binom.test
Execution halted

[vast combine]: Combining results into a single table
Smartmatch is experimental at /scratch/users/ferngonz/vast-tools/bin/Add_to_FULL.pl line 191.
cat: raw_incl/INCLUSION_LEVELS_ALT3-Mm24-n.tab: No such file or directory
cat: raw_incl/INCLUSION_LEVELS_ALT5-Mm24-n.tab: No such file or directory
cat: raw_incl/INCLUSION_LEVELS_IR-Mm24.tab: No such file or directory
[vast combine]: Final table saved as: /scratch/users/ferngonz/vast-tools/vast_out/INCLUSION_LEVELS_FULL-mm10-4.tab
[vast combine]: Deleting raw_incl/ folder
[vast combine]: Deleting raw_reads/ folder
[vast combine]: Completed Thu Oct 12 17:21:13 2023

**Comment by mirimia** [comment]
Hello,

This is a strange error. I think it's likely due to a previous issue running align. Could you please:

- send me the command you use for combine.
- do an ls -lsh in the to_combine folder and copy paste the print out?

Thanks!

**Comment by ferngonz** [comment]
You were right! I reran vast-tools align function and it fixed the error. Thank you!

**Comment by mirimia** [comment]
Great!
