### ISSUE TITLE
Is it possible to handle long-read RNA-seq data with VAST-TOOL?

### ISSUE THREAD

**Issue by happypiggyzjx** [vastgroup/vast-tools#118]
Dear VAST-TOOL Software Development Team，

Greetings! Thank you very much for developing such a great software, and now I have a small question for you: is it possible to handle long-read RNA-seq data with this software? If so, is there anything I should be aware of?
Thank you again for taking time out of your busy schedule to read this email, your professional reply really means a lot to me.

Sincerely，
Happy Piggy

**Comment by mirimia** [comment]
Hello,

It is technically possible if provided in FQ format, but not recommended.

If you want a similar quantification, exon-based, I recommend using insplico.

Cheers
Manu
