### ISSUE TITLE
Selecting microexons

### ISSUE THREAD

**Issue by pgupta3005** [vastgroup/vast-tools#121]
Hello, after obtaining the events table, I wish to filter and keep only the events of microexon inclusion/skipping in my samples. The "MIC" events under "COMPLEX" column only includes microexons up to a length 15nt. What other filters can I use to obtain microexons up to 27nt length? Would the following command suffice -

```{r}
subset(table1, COMPLEX %in% c("S", "C1", "C2", "C3", "MIC") & LENGTH <=27)
```

**Comment by mirimia** [comment]
Hello,

The best way to select microexons is to first select all exons (ie, EX in the second column, EventID) and then filter by length with column 3 LENGTH. Do not use column COMPLEX (for anything).

If you want to do it slightly better, you can download the event features in VastDB and use the reference length, which is the most supported by reads.

Thanks!
Manu

**Comment by mirimia** [comment]
By the way, I actually read your comment in detail... yes, your command will also do! Sorry! ;-)

**Comment by pgupta3005** [comment]
Thanks for the quick confirmation! Closing the issue now.
