### ISSUE TITLE
Circumventing Read Length Limitation in vast-tools

### ISSUE THREAD

**Issue by imendizabalCIC** [vastgroup/vast-tools#125]
Dear vast-tools Team,

We would like to run vast-tools on RNA-seq datasets with read length of 48bp, but we are aware that the minimum allowed is 50bp (we obtain the error: [vast align error]: Trim5 (0) cannot be applied for reads of length 48.

Could you advise us on potential options to circumvent this limitation? We are considering adding 2 "N" nucleotides to each read to reach the required length. Would this approach be a valid solution? 

Thank you for your support and for developing this valuable tool,

Isabel

**Comment by mirimia** [comment]
Hi Isabel,

Easy solution: there is an undocumented option to do this. Just add --trimLen 48. 

Keep in mind, though, that the reliability of the mapping correction will be lower, as it's done for 50-nt long mappings.

M

**Comment by imendizabalCIC** [comment]
Hi Manu,

That's awesome, I appreciate your prompt response!

Isabel
