### ISSUE TITLE
Use of uninitialized value $newOrder in Add_to_FULL.pl

### ISSUE THREAD

**Issue by mirimia** [vastgroup/vast-tools#32]
Hi Kevin,

I got this error in the new combine (Add_FULL), in the bit to reorder. It's repeated once per event, I think.

Use of uninitialized value $newOrder[0] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[1] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[2] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[3] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[4] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[5] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[6] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[7] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[8] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[9] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[10] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[11] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[12] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[13] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[16] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[17] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[20] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[21] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[22] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[23] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[24] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[25] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[26] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[27] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[28] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[29] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[30] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[31] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[32] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[33] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[38] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[39] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[44] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[45] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[50] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[51] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[52] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[53] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[54] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[55] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[56] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[57] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[58] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[59] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[60] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[61] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[66] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[67] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[70] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[71] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[74] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[75] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[80] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[81] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[82] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[83] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[84] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.
Use of uninitialized value $newOrder[85] in array slice at /nfs/users/mirimia/projects/vast-tools/bin/Add_to_FULL.pl line 140, <STDIN> line 112173.

Then, I got something similar for the combine of the expr table, but here I didn't have all the samples :

Use of uninitialized value in concatenation (.) or string at /nfs/users/mirimia/projects/vast-tools/bin/MakeTableRPKMs.pl line 71.
Use of uninitialized value in concatenation (.) or string at /nfs/users/mirimia/projects/vast-tools/bin/MakeTableRPKMs.pl line 71.
Use of uninitialized value in concatenation (.) or string at /nfs/users/mirimia/projects/vast-tools/bin

.......

I figure these are easy to correct. Would you mind, please?
Thanks.
Manu

**Comment by mirimia** [comment]
Sorry, it looks like my bad. I'll test and get back to you again in a minute. Sorry.

**Comment by mirimia** [comment]
Yep, sorry. I had some names that were inconsistent from running vast twice. Sorry!

**Comment by kcha** [comment]
No worries! =)

**Comment by kcha** [comment]
Will look into checking files with inconsistent names.

**Comment by kcha** [comment]
Fixed bug in re-ordering sample columns (b55a58d)
