### ISSUE TITLE
Error in vast-tools diff

### ISSUE THREAD

**Issue by mirimia** [vastgroup/vast-tools#33]
Hi Tim,

I'm getting this error in diff: 

Trying to load required package: optparse
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
Error in loadNamespace(name) : there is no package called ‘labeling’
Calls: plotPrint ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

It happens sometime after it analyzes (and detects as differentially included) quite a few AS events already, so I'm not sure why it happens.

Thanks,
Manu

**Comment by UBrau** [comment]
Hi,

This may or may not be related, but I've been having a similar experience on the cluster with identical jobs that UAE the package GenomicRanges either running or dying.
In this case it could be happening when diff spawns the parallel processes.

Ulrich

On Jan 9, 2015 9:50 AM, Manuel Irimia <notifications@github.com> wrote:

Hi Tim,

I'm getting this error in diff:

Trying to load required package: optparse
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
Error in loadNamespace(name) : there is no package called ‘labeling’
Calls: plotPrint ... tryCatch -> tryCatchList -> tryCatchOne ->
Execution halted

It happens sometime after it analyzes (and detects as differentially included) quite a few AS events already, so I'm not sure why it happens.

Thanks,
Manu

**Comment by timbitz** [comment]
Old version of R?  Can you check, it should say in your logged output.  Is this on the cluster? If so, which nodes?

Sent from my iPhone

On Jan 9, 2015, at 8:50 AM, Manuel Irimia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Tim,

I'm getting this error in diff:

Trying to load required package: optparse
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
Error in loadNamespace(name) : there is no package called ‘labeling’
Calls: plotPrint ... tryCatch -> tryCatchList -> tryCatchOne ->
Execution halted

It happens sometime after it analyzes (and detects as differentially included) quite a few AS events already, so I'm not sure why it happens.

Thanks,
Manu

**Comment by mirimia** [comment]
I'm running this on the CRG cluster (I'm not sure I've ever tried diff here, but I think I did). R version is 3.1.1 (2014-07-10).

I'll try on the bc cluster now to see if I get the same error.

Thx

**Comment by mirimia** [comment]
It works well in the BC cluster, with R version 3.0.1. So it might be that? (it's weird as the one that didn't work is a newer version).

**Comment by timbitz** [comment]
Is the R you are using at CRG a global install or is it your local user install?  I wouldn't think the newer R version would be a problem...

Sent from my iPhone

On Jan 9, 2015, at 1:21 PM, Manuel Irimia <notifications@github.com<mailto:notifications@github.com>> wrote:


It works well in the BC cluster, with R version 3.0.1. So it might be that? (it's weird as the one that didn't work is a newer version).

**Comment by UBrau** [comment]
Could it be a problem that the package in question is only available in 
your local install but is not compatible with the newer R version that 
is running on some nodes?

_u

**Comment by timbitz** [comment]
parallel is a core package, as far back as of 2.14 I think.

Sent from my iPhone

On Jan 9, 2015, at 2:07 PM, Ulrich Braunschweig <notifications@github.com<mailto:notifications@github.com>> wrote:

Could it be a problem that the package in question is only available in
your local install but is not compatible with the newer R version that
is running on some nodes?

_u

**Comment by mirimia** [comment]
As far as I understand it:
- This is the global R installation of the cluster (/usr/bin/R)
- I'm running this in the main node (not as a submitted job), so it's not related to other versions in other nodes (I've just submitted the job now, to see if it runs differently).

Also, why do you assume there is a problem with "parallel" (asking out of ignorance)? It seems to me it loads correctly, then it runs for a while (~30 minutes, selecting ~200 events) and at some point it crashes with this error:

Error in loadNamespace(name) : there is no package called ‘labeling’ Calls: plotPrint ... tryCatch -> tryCatchList -> tryCatchOne ->

I mean, it's not that it crashes right after trying to upload "parallel".

**Comment by UBrau** [comment]
Sure, but isn't this is about 'labeling'?
_u

**Comment by timbitz** [comment]
Unless its a problem with grid...

Sent from my iPhone

On Jan 9, 2015, at 2:07 PM, Ulrich Braunschweig <notifications@github.com<mailto:notifications@github.com>> wrote:

Could it be a problem that the package in question is only available in
your local install but is not compatible with the newer R version that
is running on some nodes?

_u

**Comment by timbitz** [comment]
Yah that might be grid.  Hard to figure it out from an iphone... Will look into it when i have a computer.

Sent from my iPhone

On Jan 9, 2015, at 2:17 PM, Ulrich Braunschweig <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure, but isn't this is about 'labeling'?
_u

**Comment by timbitz** [comment]
OK.   The problem looks to be dependencies: 'labeling' is a dependent package that is installed by default when you install ggplot2 if you require dependencies.  I thought the loadPackages function required dependencies but it looks like maybe not.  So I have added that now.

**Comment by mirimia** [comment]
Thanks. I've pulled the last change but it still gives the error. Should I do something else? (like, re-install any bit?).

M

**Comment by timbitz** [comment]
Yes.  You can probably just open R and install.packages('labeling').  Or delete ggplot2 and re-install with the script which should now also install that dependency.  =
