### ISSUE TITLE
3'-bias file open error

### ISSUE THREAD

**Issue by UBrau** [vastgroup/vast-tools#40]
There appears to be a problem file I/O since introduction of the 3'-bias analysis.

Sample output:
## Tue May 19 12:59:16 2015 #################################################################
==> vast-tools.o18985318
==> Run command    : /home/blencowe/blencowe1/ulrich/AS_PIPE_S_dev/vast-tools align --sp Mmu --dbdir /home/blencowe/blencowe1/ulrich/AS_PIPE_S_dev/ -c 2 -o vast/ --expr raw/combined/N2A_siMbnl1_plus_2_R1.fq.gz raw/combined/N2A_siMbnl1_plus_2_R2.fq.gz
==> Execution host : node27.ccbr.utoronto.ca
[vast align]: Setting output directory to vast/
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /home/blencowe/blencowe1/shared/Ulrich/RNAseq.Hong.CGR8.N2A.150401/combi/vast/tmp!
[vast align]: Mapping reads against mRNA sequences
[vast align]: Calculating cRPKMs
'# reads processed: 74874493
'# reads with at least one reported alignment: 50092377 (66.90%)
'# reads that failed to align: 19401424 (25.91%)
'# reads with alignments suppressed due to -m: 5380692 (7.19%)
Reported 50092377 alignments to 1 output stream(s)
Can't open expr_out/N2A_siMbnl1_plus_2_R1: No such file or directory at /home/blencowe/blencowe1/ulrich/AS_PIPE_S_dev/bin/expr_RPKM.pl line 35, <> line 50115044.
[vast align]: Trimming fastq sequences to 50 nt sequences
[vast trim]: Total processed reads: 74874493
[vast trim]: Total valid fwd reads: 74874493
[vast trim]: Total valid rev reads: 74874493
[vast align]: Doing genome substraction
[ ABBREVIATED ]

It seems to be happening here:
verbPrint "Calculating cRPKMs\n";
sysErrMsg "$cmd | $binPath/expr_RPKM.pl - $dbDir/EXPRESSION/$species"."_mRNA-$le.eff expr_out/$root > expr_out/$root\.cRPKM";

The cRPKM table that is produced seems OK, but the full content of the .3bias file in this example was this:
N2A_siMbnl1_plus_2_R1	500nt	15.30	18.22	19.94	22.07	24.46	5908
N2A_siMbnl1_plus_2_R1	1000nt	15.24	17.88	20.04	22.34	24.50	1643

**Comment by kcha** [comment]
@mirimia, can you take a look at this?

**Comment by mirimia** [comment]
It's a harmless (and expected) error. I'll try to find out a way to avoid it...

**Comment by mirimia** [comment]
(I'll leave the issue open so I remember it)

**Comment by mirimia** [comment]
Just added a fix for this.
