### ISSUE TITLE
Differences in IR events listed in output

### ISSUE THREAD

**Issue by UBrau** [vastgroup/vast-tools#41]
The output table contains different IR events depending on the input. Seems to be a problem with either (a) merging of events when combining IR data, or (b) merging IR with rest of pipeline.

**Comment by mirimia** [comment]
My understanding was that only (and all) the events in VASTDB/Hsa/TEMPLATES/Hsa.FULL.Template.txt.gz would be included the final sample...

So I guess the problem occurs when generating the pre-final "IR" table. Again, though, this is supposedly done using "Hsa.IR.Template.txt"??

**Comment by UBrau** [comment]
Yes, I thought so too. As it turns out though, it's not the case.
I had not noticed earlier, but this is not something new (as my previous 
email suggested) but there were differences all along apparently. Som IR 
events get dropped.

I just noticed another thing that I guess should not be as it is: The 
full event templates ($sp.FULL.Template.txt) contain ~ 20,000 more 
introns than the intron templates ($sp.IR.Template.txt) for both mouse 
and human. It seems like the full templates never incorporated the 
'latest' version of the IR templates -  or did we do that to maintain 
compatibility with the paper?

Either way, the IR events which were dropped in one case but not another 
are present in both templates, and they are also still there in the 
INCLUSION_LEVELS_IR-Mmu10.tab file. So
they must have been dropped while merging the different modules.

Ulrich

**Comment by mirimia** [comment]
Fun. And these extra are printed as "NA\tN,N,N..." I guess?

**Comment by mirimia** [comment]
I seem to recall that we discussed two options for IR:

1) Use the events in the paper (IR.template).
2) Allow a new filtering as you did in the paper, but with whatever samples used (the "full potential set" would be those in FULL).  I'm not sure this was ever implemented (but perhaps it's --stringentIR in align?).



M

**Comment by UBrau** [comment]
Our intention was to do (2), and that's what the IR templates are. The 
reason was that there are some events that would always be pulled out 
due to problematic overlap, and others (the ones that never passed QC) 
that would be difficult for users to judge if they don't have an equally 
broad collection of samples as we did.

It could be that the FULL templates were made before this was done and 
never changed.

_u
