### ISSUE TITLE
Analysis never ends

### ISSUE THREAD

**Issue by attakata** [vastgroup/vast-tools#42]
We are highly interested in your vast-tools. However the analysis always stuck at the point below (we have waited for more than a week).

vast-tools align test/1.fastq test/2.fastq 
[vast align]: Setting output directory to /mnt/dbs03/home/takata/analysis/vast-tools/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /mnt/dbs03/home/takata/analysis/vast-tools/vast_out/tmp!
[vast align]: Trimming fastq sequences to 50 nt sequences
[vast trim]: Total processed reads: 2500
[vast trim]: Total valid fwd reads: 2500
[vast trim]: Total valid rev reads: 2500
[vast align]: Doing genome substraction

This was the case even if we reduced the number of reads to 2500 and used multiple 2.4GHz cores.

Required software is seemingly installed successfully as follows.

./install.R 
Using R version 3.2.1 (2015-06-18)
Looking for VAST Database [VASTDB]
Found what appears to be VASTDB.. OK
Trying to load required package: MASS
Trying to load required package: getopt
Trying to load required package: optparse
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
Trying to load required package: devtools
Loading required package: psiplot
Setting vast-tools permissions... success!
/usr/bin/bowtie
Found bowtie... Everything looks --OK

We appreciate if you could tell us how long it usually take to finish the analysis and/or whether our environment may have some problem.

**Comment by mirimia** [comment]
This is strange. It seems to be stuck on the first bowtie run. I guess you had run bowtie before without any problems?
Does it create the trimmed fasta file normally? 
Perhaps it could have to do with the namings of the fastq files (but i doubt it). Try just in case to run it with compressed fastq files named "reads1.fq.gz" or so.

Thanks

**Comment by kcha** [comment]
Hi @attakata, can you also try running the analysis using the supplied test data with VASTDB? The FASTQ files should be located under: `<your VASTDB path>/Hsa/FASTQ/`

**Comment by attakata** [comment]
Dear mirmia and kcha,
Thanks a lot for your suggestion. Installation of bowtie and setting of PATH looks to have some problem. When I reinstalled it and add the bowtie directory to PATH vast-tools align works successfully. 

Best,
