### ISSUE TITLE
questions about vast-tools align and diff

### ISSUE THREAD

**Issue by Rahel14350** [vastgroup/vast-tools#44]
Dear Tim,
-As I have 10 levels of data and afterwards I need to do differential splicing analysis on the output data. Do you still recommend me to use Diff? Or is it possible to import IR counts or exon skipped counts in DESeq2 and do the differential analysis there, if yes which column in each output showing the row count for each one?

-Sorry for many question, but your answers will help me a lot.
Many thanks in advance,
Rahel

**Comment by timbitz** [comment]
As is stated in the documentation, you can use `vast-tools diff` for any number of replicates, but can only make a comparison between two groups at a time `-a rep1,rep2,...,repN -b repA,repB,repC`.   

Regarding DEseq/DEXseq, Again-- there are fundamental differences between `vast-tools` vs. `DESeq/DEXseq` and their input/output are not compatible (nor can the be coerced to be) in any way shape or form.

**Comment by Rahel14350** [comment]
Dear Tim,

Many many thanks for your reply. I started running Diff for differential analysis and it works very well.

Kind regards,
Rahel
