### ISSUE TITLE
Calcaulating the overall PSI value between samples

### ISSUE THREAD

**Issue by Rahel14350** [vastgroup/vast-tools#46]
Dear Tim,
I used vast-tools for AS analysis between two tissue groups. In diff-output I have the PSi values for each group of samples (Tissue A and B) per AS event calculated by posterior distribution of replicates in each tissue group. 
If I want to compare all AS events in tissue A to tissue B (e.g. comparing all EXSK events between tissue A and B), which kind of statistical test do you recommend to reach to one PSI value per group of samples to be shown for example in a bar plot. Is some sort of ANOVA suitable to cover the mean and variance of PSI between groups?

Many thanks in advance,
Rahel

**Comment by timbitz** [comment]
I believe the answers you are looking for are detailed in the manual [here](https://github.com/vastgroup/vast-tools#differential-splicing-analysis).  Please see the `diff` section on *Output Format*.  The multi-replicate point estimates are given, as is the expected value for the difference, and the probability that there exists a difference greater than some input value `-m`.   That is in itself meant to be a statistical test, and is not meant to work with ANOVA or any other type of frequentist test.

**Comment by Rahel14350** [comment]
Dear Tim,

Thanks for your prompt reply. I did read the vast-tools manual and references but maybe I did not explain good my question. In the Irimia et al., 2014 there are some bar plots that the Y-axis is showing the e.g. No. of AS exons in different tissues or % of retained introns in different tissues. In my diff-out put, there is 9000 event with 9000 PSI values for each tissue.  if I want to draw some bar plot or box plot that it shows in the y-axis the percentage of intron retention (PIR) in tissueA (considering all replicates and events) and tissue B, Then how I can reach to a number per tissue?

Or for global PIR distribution in each tissue, I am totally wrong by looking at diff output and I need to look for this number from combine output? But it is more difficult there because I have PIR value per event per replicate ....

I hope I explained it clear this time.
Many thanks in advance for your time,
Rahel

**Comment by mirimia** [comment]
Dear Rahel,

This forum is meant only to clarify doubts on the use of vast-tools. What you are asking goes beyond vast-tools, and it is related to your specific scientific questions. 
How these plots are generated is described in the Methods section of those papers (I actually think you are referring to Braunschweig et al). 

Best regards,
Manu
