### ISSUE TITLE
Folders with spaces are problematic

### ISSUE THREAD

**Issue by nuno-agostinho** [vastgroup/vast-tools#51]
The program isn't prepared to handle folders with spaces in their names. When trying to run VAST-TOOLS in such a folder, the program splits the folder path in the first space and tries to look for the input files there. This causes a warning that states "input files" don't exist.

For example, trying to run VAST-TOOLS in a directory named "monty python" returns the following output:

```
[vast align error]: Input file python/vast_out does not exist!
```

This is easily solved by removing spaces from the name of the working folder.

**Comment by kcha** [comment]
Hi @nuno-agostinho,

We'll look into this for the next release, but in the meantime it's probably best that you avoid spaces in your folders.
