### ISSUE TITLE
[vast align error]: rm -50.fa.gz Failed in RunDBS_1.pl!

### ISSUE THREAD

**Issue by fenguita** [vastgroup/vast-tools#53]
Dear All

I got this anoying error when I tried to run vast-tools in align mode. Any clues about what's going on?. Something that I am doing is wrong ? .
Thanks. Paco

[vast align]: Using VASTDB -> /home/fenguita/work/vast-tools/Hsa
[vast align]: Setting output directory to /home/fenguita/work/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /home/fenguita/work/vast_out/tmp!
[vast align]: Trimming fastq sequences to 50 nt sequences
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RunDBS_1.pl line 358.
[vast trim]: Total processed reads: 118845011
[vast trim]: Total valid fwd reads: 108488609
[vast trim]: Total valid rev reads: 118845011
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RunDBS_1.pl line 359.
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RunDBS_1.pl line 367.
[vast align]: Doing genome subtraction
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RunDBS_1.pl line 387.
[vast align]: Mapping reads to the "splice site-based" (aka "a posteriori") EEJ library and Analyzing...
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
[vast align]: Mapping reads to the "transcript-based" (aka "a priori") SIMPLE EEJ library and Analyzing...
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
[vast align]: Mapping reads to the "transcript-based" (aka "a priori") MULTI EEJ library and Analyzing...
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
[vast align]: Mapping reads to microexon EEJ library and Analyzing...
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
[vast align]: Mapping reads to intron retention library (version 1)...
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RI_summarize.pl line 51.
gzip: invalid option -- '0'
Try `gzip --help' for more information.
Option root requires an argument
Warning: Could not find any reads in "-"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)

No alignments
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RI_summarize_introns.pl line 49.
Use of uninitialized value $root in concatenation (.) or string at /home/fenguita/work/vast-tools/bin/RI_summarize_introns.pl line 51.
[vast align]: Cleaning -50.fa.gz files!
rm: invalid option -- '5'
Try 'rm ./-50.fa.gz' to remove the file ‘-50.fa.gz’.
Try 'rm --help' for more information.
[vast align error]: rm -50.fa.gz Failed in RunDBS_1.pl! at /home/fenguita/work/vast-tools/bin/RunDBS_1.pl line 90.

**Comment by mirimia** [comment]
What is the name of your fastq file? It looks like a formatting error. (Some constraints are specified in the README). Also, could you provide the exact run command? Thanks

**Comment by fenguita** [comment]
Hi... thanks for your help. The command line that I used is

/usr/local/vast-tools/vast-tools align A6-Tr-1.txt.gz A6-Tr-2.txt.gz -c 4 -readLen 50 -dbDir /usr/local/vast-tools/

**Comment by mirimia** [comment]
Hi,

Yes, that's the issue. The fastq files have to be named "fastq", "fq", "fasta" or "fa" at this point. I can make the change to allow txt in the next release.

Also, I would strongly recommend changing the "-" to "_" as indicated in the README.

Thanks
Manu

**Comment by mirimia** [comment]
Just to be sure. I recommend you name your samples, for example:

A6_Tr_1.fq.gz

**Comment by fenguita** [comment]
Thanks Manu... I got the files renamed and the software is running. I will let you know about the results.
