### ISSUE TITLE
Problems w/ vast-tools diff

### ISSUE THREAD

**Issue by nunolbmorais** [vastgroup/vast-tools#54]
Hi guys,

For the last few weeks, we cannot run vast-tools diff, even after making sure vast-tools, R and all the required packages are up-to-date. We have tried it with different datasets and different combination of parameters and we always get the same error message:
Error: Unknown parameters: x
Execution halted

One guess is that it could be related with the recent upgrade of ggplot2 to version 2.0.

If we ask for more than one core with the -c option, we get this (8 cores):
Error in plotListed[[it]][[5]] : subscript out of bounds
In addition: Warning message:
In mclapply(1:length(lines), function(i) { :
  scheduled cores 4, 1, 5, 6, 3 encountered errors in user code, all values of the jobs will be affected
Execution halted

Please let me know if there's any way I can help or if you need more info.

Best wishes,
Nuno

**Comment by timbitz** [comment]
Hi Nuno,
   Thanks for letting me know.  You are of course correct, I had not yet updated to ggplot2 version 2.0, and there was some deprecated syntax in there.  I have now fixed the syntax to work for ggplot 2.0, as of 30edcdb.
-t

**Comment by rhugh-white** [comment]
I am receiving the same error when using vast-tools diff (version 1.1.0), but only when using the --paired=TRUE option, with paired=FALSE the script runs without error.

Rupert
