### ISSUE TITLE
Sample IDs with Paired End Reads and cRPKM calculations

### ISSUE THREAD

**Issue by skptic** [vastgroup/vast-tools#55]
Very minor issue, when running `vast-tools align` with paired end-reads I noticed the sample id was including the `_1` mate tag in all the output files. 

In my hands, for example:
`vast-tools align SRR493368_1.fastq SRR493368_2.fastq `

resulted in files:
SRR493368_1.exskX, SRR493368_1.eej2 etc...

From the README I would expect the resulting files to be SRR493368.exskX

> Reads must be given to the program such that vast-tools align fwd_mate_1.fq.gz rev_mate_2.fq.gz refers to two fastq files of identical line number where Read1 from file_1 is mated to Read1 from file_2.

As far as I can tell, the issue is restricted to the regex in RunDBS_1.pl, for example:
```
    $fileName1` =~ /(\S+)\.(fastq|fq|fasta|fa)(\.gz)?/; 
    $root = $1;
```

I have made an ugly quick fix to my fork [here](https://github.com/skptic/vast-tools/blob/master/bin/RunDBS_1.pl#L208-273) by modifying the regex whenever $root is assigned ie:
```
    if ($pairedEnd) {
    $fileName1 =~ /(\S+)(_1)\.(fastq|fq|fasta|fa)(\.gz)?/; 
    $root = $1;
    }
```

Also, I probably don't understand it correctly, but is the expression analysis (cRPKMs) only performed on the first reads file `$fq1` [here](https://github.com/skptic/vast-tools/blob/master/bin/RunDBS_1.pl#L332-343)? I can't find where `$fq1` could reference the second reads file. If this is true, it was not obvious to me in the README.

Enjoying using the software

**Comment by mirimia** [comment]
Hi Evan,

You're right, but we kept it that way because many people may name their samples using _1 to indicate replicates, for instance (something I always try to avoid). What I do is to label forward/reverse reads by _R1 and _R2, and clean the names after running. 

RE cRPKMs, yes, it is only done for the $fq1 file. I'll modify the README to make it clear.

Thanks!
Manu

**Comment by skptic** [comment]
Thanks Manu,

This is great, that is exactly what I wanted to know.

I'm developing a Nexflow pipeline for the basic VAST-TOOLS procedure [here](https://github.com/skptic/vast-tools-nf) and finding everything very straight forward.

Thanks so much for the quick response,

Evan
