### ISSUE TITLE
question baout trimming step.

### ISSUE THREAD

**Issue by TOTTW** [vastgroup/vast-tools#61]
Dear All,
My RNAseq data are stranded paired with 50 bp length or less than . In the trimming step are the cutted to 50 bp. There is always an error! I want to know is these RNAseq data can used as input for vast-tools?
Many thanks in advance.

Best,
Mengyuan Yang

**Comment by mirimia** [comment]
Dear Mengyuan,

In principle, it should run the trim and use ONLY those reads that are 50. If all of them are 49 or smaller, then it won't complain. 

There is an undocumented trick to get around this, but it comes with potentially more false positives, depending on how much you lower this value. You can do run vast-tools align with: --trimLen 49 or 48.

I'd adjust it depending on your read length distribution (e.g. do you have a sense of what % of you reads are >=48 or >=49?).

Thanks
Manu

**Comment by TOTTW** [comment]
Thanks Manu..it's helpful. All my read length are  between 48 to 50. I run vast-tools align with: --trimLen 48. And the software is running.
