### ISSUE TITLE
How to call vast-tools align with Dre

### ISSUE THREAD

**Issue by alicezyj1** [vastgroup/vast-tools#64]
Hi there,

This is just a question about how to use the new version of vast-tools/3.1.0 to analyze zebrafish RNA-seq data. I used the original version of vast-tools to analyze human data by calling:
                vast-tools align file_1.fastq.gz file_2.fastq.gz --sp Hsa -c 32 --expr
There are three options for --sp Hsa/Mmu/Gga
I downloaded the new version of vast-tools which supports the analysis of zebrafish and sea urchin RNA-seq data. But there are still the original three options for --sp. 
I am wondering if there is any other way to write this command for analysis of zebrafish data? 

Many thanks!

**Comment by mirimia** [comment]
Hey,

Sorry, the help text wasn't updated. It takes any of the available species (I changed it to --sp Hsa/Mmu/etc).

You can run vast-tools already for zebrafish using --sp Dre.

Cheers
Manu
