### ISSUE TITLE
align issue

### ISSUE THREAD

**Issue by briankalish** [vastgroup/vast-tools#67]
Hello,
I am a new VAST-tools user and I am having issues with the align function. I have paired-end reads. My original sequencing output was 8 fastq files (4 lanes of each read) per sample. I concatenated the four lane files into into individual fastq files for each read. While the initial alignment seems to work fine, I encounter a problem when the reads are reverse-complemented. They are supposed to be written to a tmp file (~/vast_out/tmp/tmp_read_files/), but my reads are not written to this directory. This then creates an error for subsequent steps (eg. mapping reads against mRNA sequences) that call the file from this directory. Any thoughts on how to fix this issue?

Thanks in advance,
Brian

**Comment by mirimia** [comment]
Hi Brian,

This is strange, indeed. Could you please send me more details? Mainly, the command you use to run align and whether you're working on mac/linux? 

Thanks
Manu

**Comment by briankalish** [comment]
Hi Manu,

I am running VAST-tools on a linux-based high performance computing cluster at Harvard, since I figured the files were large and best not used locally. I have pasted my command and the output below. Of note, the alignment percentage (~30%) is much lower than the alignment I get when I align normally with STAR. As I said in my post, the writing of the reverse-complemented reads to the tmp folder does not occur, as far as I can tell.


/n/scratch2/btk4/vast/vast-tools/--[ 180417_18:32:05 ]==>   /n/scratch2/btk4/vast/vast-tools/vast-tools align NT_6A_1.fq NT_6A_2.fq -sp Mmu --expr
[vast align]: Input RNA-seq file(s): /n/scratch2/btk4/vast/vast-tools/NT_6A_1.fq and /n/scratch2/btk4/vast/vast-tools/NT_6A_2.fq
[vast align]: Most common read lengths detected for fq1 & fq2: 75 (68.46%) and 75 (67.68%)
[vast align]: Using VASTDB -> /n/scratch2/btk4/vast/vast-tools/VASTDB/Mmu
[vast align]: Setting output directory to /n/scratch2/btk4/vast/vast-tools/vast_out
[vast align]: Setting tmp directory..
[vast align]: Set tmp directory to /n/scratch2/btk4/vast/vast-tools/vast_out/tmp!
# reads processed: 100000
# reads with at least one reported alignment: 31597 (31.60%)
# reads that failed to align: 66273 (66.27%)
# reads with alignments suppressed due to -m: 2130 (2.13%)
Reported 31597 alignments
[vast align]:    fraction of first reads mapping to fwd / rev strand : 0.0099 / 0.9901
# reads processed: 100000
# reads with at least one reported alignment: 30120 (30.12%)
# reads that failed to align: 67850 (67.85%)
# reads with alignments suppressed due to -m: 2030 (2.03%)
Reported 30120 alignments
[vast align]:    fraction of second reads mapping to fwd / rev strand : 0.9883 / 0.0117
[vast align]:    reverse-complementing reads from /n/scratch2/btk4/vast/vast-tools/NT_6A_1.fq; writing into /n/scratch2/btk4/vast/vast-tools/vast_out/tmp/tmp_read_files/NT_6A_1.fq
[vast align]: Mapping RNAseq reads against mRNA sequences
[vast align]: Calculating cRPKMs
cat: /n/scratch2/btk4/vast/vast-tools/vast_out/tmp/tmp_read_files/NT_6A_1.fq: No such file or directory
[vast trim]: Total processed reads: 0
[vast trim]: Total valid fwd reads: 0
Error: reads file does not look like a FASTQ file
Command: /n/app/bowtie/1.2.2/bowtie-align-s --wrapper basic-0 --norc -q -p 1 -m 1 -v 2 /n/scratch2/btk4/vast/vast-tools/VASTDB/Mmu/EXPRESSION/mRNA -
Illegal division by zero at /n/scratch2/btk4/vast/vast-tools/bin/expr_RPKM.pl line 143, <> line 22667.
[vast align error]: cat /n/scratch2/btk4/vast/vast-tools/vast_out/tmp/tmp_read_files/NT_6A_1.fq | /n/scratch2/btk4/vast/vast-tools/bin/Trim.pl --once --targetLen 50 -v | bowtie --norc -q -p 1 -m 1 -v 2 /n/scratch2/btk4/vast/vast-tools/VASTDB/Mmu/EXPRESSION/mRNA - | /n/scratch2/btk4/vast/vast-tools/bin/expr_RPKM.pl - /n/scratch2/btk4/vast/vast-tools/VASTDB/Mmu/EXPRESSION/Mmu_mRNA-50-SS.eff expr_out/NT_6A_1 > expr_out/NT_6A_1.cRPKM Failed in RunDBS_1.pl! at /n/scratch2/btk4/vast/vast-tools/bin/RunDBS_1.pl line 186.?

________________________________

**Comment by mirimia** [comment]
I see.

@aghr could you please take care of it? Thanks

**Comment by aghr** [comment]
Dear Brian, I fixed the bug and committed to master. Please let me know if you should have further issues by emailing to andre.gohr@gmail.com . Many thanks. André
