### ISSUE TITLE
VastDB library for Drosophila melanogaster (dm6)

### ISSUE THREAD

**Issue by Kennyrebelo** [vastgroup/vast-tools#70]
Hello,

Not really a technical issue, I was wondering if you had a VastDB library for the dm6 genome. Even if not yet made public if you could share something in beta-state that I could use to run vast-tools for drosophila sequencing data it would be very helpful.

Thank for your time,
Kenny

**Comment by mirimia** [comment]
Hi Kenny,

We will release it soon. Please send me an email (mirimia@gmail.com).

Cheers
Manu
