### ISSUE TITLE
to_combine: zero inclusion/exclusion reads error

### ISSUE THREAD

**Issue by araposo** [vastgroup/vast-tools#71]
I have run Vast-tools 1.3.0 for 15 data sets in Mmu, with previous VastDB files and had no problems.
I have now repeated the analysis with 2.0.2 and the updated annotation. (vastdb.Mmu.16.02.18.tar.gz), and I can't get it to finish the score table. I appears it's because one of the files has no IR reads (the species is the same for all of the other files, running sbatch on SLURM machine):
  
Merging IR of 15 sample(s)...
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
sample_1-E15.SE1 
[vast combine]: Building Table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
Trying to load required package: optparse
Merging IR of 15 sample(s)...
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
[vast combine]: Building quality score table for intron retention (version 2)
Error: Looks like an error: all IR events of sample sample_1-E15.SE1 have zero inclusion and zero exclusion reads. Did you use the correct species?
Execution halted
[vast combine error]: /root/software/vast-tools/bin/RI_MakeTablePIR.R --verbose 1 -s /genomes/mm9/VastTools2/Mmu --IR_version 2 -c /vast_out/to_combine -q vast_out/to_combine/Coverage_key_v2-Mmu15.IRQ -o /vast_out/raw_incl Failed in RunDBS_2.pl! at /root/software/vast-tools/bin/RunDBS_2.pl line 53.

**Comment by mirimia** [comment]
Hello,

I was also getting this for some samples as well. @UBrau (and perhaps @aghr), could you please look at that? 

Thanks
Manu

**Comment by UBrau** [comment]
Hi @araposo,
Can you make the output files from _align_ that you were using available (e.g., Dropbox link)? Mailto: u.braunschweig@utoronto.ca

**Comment by mirimia** [comment]
Could you please also paste the output of vast-tools _align_? I.e. whether it gave any errors in the mapping steps.

**Comment by araposo** [comment]
Hi,
sorry about the delay.
i'm giving you the slurm-outs during vast-align, seems to be happening at gzip step: 
[slurm-590340_1E15.out.txt](https://github.com/vastgroup/vast-tools/files/2170361/slurm-590340_1E15.out.txt)
[slurm-590341_5P0.out.txt](https://github.com/vastgroup/vast-tools/files/2170362/slurm-590341_5P0.out.txt)
[slurm-590343_1P0.out.txt](https://github.com/vastgroup/vast-tools/files/2170363/slurm-590343_1P0.out.txt)
[slurm-590344_1P5.out.txt](https://github.com/vastgroup/vast-tools/files/2170364/slurm-590344_1P5.out.txt)

this then produces files for to_combine with 000/ne values, which break the pipe.
i'll try to upload these too.

**Comment by araposo** [comment]
examples:

[sortedNsorted_5-P0.PP.SE1.IR.summary_v2.txt](https://github.com/vastgroup/vast-tools/files/2170427/sortedNsorted_5-P0.PP.SE1.IR.summary_v2.txt)
[sortedNsorted_1-P0.PP.SE1.IR.summary_v2.txt](https://github.com/vastgroup/vast-tools/files/2170428/sortedNsorted_1-P0.PP.SE1.IR.summary_v2.txt)
[sortedNsorted_5-P0.PP.SE1.IR.summary_v2.txt](https://github.com/vastgroup/vast-tools/files/2170430/sortedNsorted_5-P0.PP.SE1.IR.summary_v2.txt)
[sortedNsorted_1-E15.PP.SE1.IR.summary_v2.txt](https://github.com/vastgroup/vast-tools/files/2170421/sortedNsorted_1-E15.PP.SE1.IR.summary_v2.txt)
[sortedNsorted_1-P5.PP.SE1.IR.summary_v2.txt](https://github.com/vastgroup/vast-tools/files/2170422/sortedNsorted_1-P5.PP.SE1.IR.summary_v2.txt)

**Comment by araposo** [comment]
(sorry)

**Comment by mirimia** [comment]
Have you tried re-running the samples? It seems a vast-tools-independent problem, somehow.

**Comment by araposo** [comment]
i've run align 2 times so far. unfortunately, didn't take note at first time which files were problematic. but, as i said, the earlier vast-tools version didn't give me any trouble.
running it again.

**Comment by mirimia** [comment]
True. That's important. Although from the log files I see the reads are not strand specific, so v2 should be identical to v1 here. Strange. 

When you run it in v1, you also started from uncompressed reads, right?

**Comment by araposo** [comment]
they're the same files: paired-end, not strand-specific.

**Comment by araposo** [comment]
uncompressed

**Comment by UBrau** [comment]
@araposo, could you provide us with sample data for which you see the error?

**Comment by araposo** [comment]
gladly, but the fastq files are 10GB each x2 (paired-end)... 
in any case, results are not consistent: on this re-run, i don't even get the raw_incl/reads folders. 
another difference, for one of the files ("second" for re-run):
[first_1-E15.PP.SE1.IR2.txt](https://github.com/vastgroup/vast-tools/files/2189284/first_1-E15.PP.SE1.IR2.txt)
[second_1-E15.PP.SE1.IR2.txt](https://github.com/vastgroup/vast-tools/files/2189285/second_1-E15.PP.SE1.IR2.txt)

[slurm-first_1E15.out.txt](https://github.com/vastgroup/vast-tools/files/2189295/slurm-first_1E15.out.txt)

[slurm-second_1E15.out.txt](https://github.com/vastgroup/vast-tools/files/2189336/slurm-second_1E15.out.txt)

**Comment by UBrau** [comment]
I'm not sure what these files are... they seem to be logs from running two different input files (P5 and E15, see 2nd line). The 'unexpected end of file' warnings make me think that there could be an issue on your system that caused writing to these files to be interrupted. Was your disk full? Could a connection have been broken when copying files?
