### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by fgypas** [vastgroup/vast-tools#74]
Hi

Is there a Dockerfile available for vast-tools?
In this way, one could skip the installation process.

Thank you in advance
Foivos

**Comment by evanfloden** [comment]
I did one a while ago for the dependencies here: 
https://github.com/evanfloden/vast-tools-nf/blob/master/Dockerfile

Looking back I didn't include vast-tools itself. Not sure why not but it would be easy enough to add a git clone.

**Comment by fgypas** [comment]
Thanks @evanfloden . At least it is a good starting point. So the repo I found at docker hub (https://hub.docker.com/r/skptic/vasttools/) is based on a different Dockerfile? vast-tools is available there.

**Comment by evanfloden** [comment]
It will be the same one I believe as I created that one.

But I should update the Dockerfile in my repo now anyway.

Gimmie 15 min.

**Comment by evanfloden** [comment]
Updated and included the vast-tools repo in the image.

Note that this does not take care of the VASTDB which should be downloaded and linked.

I will attempt to update the [workflow](https://github.com/evanfloden/vast-tools-nf/blob/master/Dockerfile) which takes care of these details.

Image is on dockerhub `evanfloden/vasttools:v2.0.2` and Dockerfile is [here](https://github.com/evanfloden/vast-tools-nf/blob/master/Dockerfile).

**Comment by fgypas** [comment]
I tried it and I think there is a problem with Bowtie. It's not in PATH. Does it work for you? And when I run in the container:

`bowtie-1.2.1.1/bowtie --help`

I get:

> /usr/bin/env: python: No such file or directory

**Comment by fgypas** [comment]
I think that python is a dependency. I would change the bowtie part to the following:

`RUN apt-get install -y python && \
`    
`wget -q https://github.com/BenLangmead/bowtie/releases/download/v1.2.1.1/bowtie-1.2.1.1-linux-x86_64.zip && \
`   
 `unzip bowtie-1.2.1.1-linux-x86_64.zip && \
`   
 `rm bowtie-1.2.1.1-linux-x86_64.zip && \
`   
 `ln -s /bowtie-1.2.1.1/bowtie /usr/bin/bowtie`

**Comment by evanfloden** [comment]
Thanks! I have added that line to the above Dockerfile and pushed the image to dockerhub.

Let me know if there are any other problems.

**Comment by fgypas** [comment]
Thanks a lot. I think it works just fine now.
