### ISSUE TITLE
Add quality filtering to diff

### ISSUE THREAD

**Issue by UBrau** [vastgroup/vast-tools#79]
Add an option to _diff_ to do filtering based on quality scores. This would also reflect behaviour of _compare_.

**Comment by mirimia** [comment]
Hi @UBrau, 

Was this ever done? Shall I close the issue?

**Comment by UBrau** [comment]
I got started but it lead to really bad performance issues (run time) that I wasn't able to fix. Maybe better close for now.

**Comment by mirimia** [comment]
OK, thanks!
