### ISSUE TITLE
alternative splicing in one group

### ISSUE THREAD

**Issue by CLeib** [vastgroup/vast-tools#81]
Hello,
Is there a way to get LeafCutter to work on a single set of data, instead of comparing two groups (so as to see the alternative splicing events within a sample/repeats)?

Thanks in advance

**Comment by mirimia** [comment]
Well, it's great you ask here, since that's one of the advantages of vast-tools ;-). But, unfortunately, no idea about LeafCutter...

**Comment by CLeib** [comment]
Sorry! wrong group
