### ISSUE TITLE
vast-tools combine failed

### ISSUE THREAD

**Issue by flolebill** [vastgroup/vast-tools#91]
Hi Dr. Irimia and the vast-tools team,

I'm using the vast-tools for the first time, and I've succeeded in the alignement so far.
My experiment consists on human cells +/- my protein of interest (ARGLU1) and +/- my drug of interest (Dex), all conditions in duplicate.
The sequencing was performed on NovaSeq 150 PE.

On the attached pictures, you can see the different outputs from the alignement, a screenshot of my command for the combine step and the result I've obtained. I've precised on the command the location of /vast_out as I thought that could be the problem, but even without a -o option, I had the same result.

Please, could you help me solve this issue? 

In advance, thank you and have a good day,
Florian
![Screenshot from 2020-07-09 22-06-25](https://user-images.githubusercontent.com/39013928/87161149-144fa880-c292-11ea-96cf-edb678a5a90b.png)
![Screenshot from 2020-07-09 22-03-56](https://user-images.githubusercontent.com/39013928/87161151-14e83f00-c292-11ea-892c-68e0fe186c78.png)
![Screenshot from 2020-07-09 22-05-51](https://user-images.githubusercontent.com/39013928/87161152-1580d580-c292-11ea-9e4e-42f1bca33a04.png)

**Comment by mirimia** [comment]
Hello,

It seems the align step did not work well. If you notice, the *eej2 files are empty. Can you please paste the logs of the align commands? Perhaps it was a memory issue, so you can increase the limit a bit (e.g. 8G should be enough). 

Thanks
Manu

**Comment by flolebill** [comment]
Here is a screenshot of an alignment that is currently running.
I don't know if it is relevant, but I can say that the alignment for one pair of samples take more than 14h. 
If I want to relaunch the alignment while increasing the memory limit, can I stop the ongoing alignment?
Thank you for your help!

![Screenshot from 2020-07-10 10-09-10](https://user-images.githubusercontent.com/39013928/87163708-c89efe00-c295-11ea-83ff-bffec10b59f5.png)

**Comment by mirimia** [comment]
Hello,

So far, it's looking OK, but it didn't reach the part where it generates the eej2 files. Could you attach any of the other files (.e.g *micX, *exskX and *IR2).

A note aside: could you run the aligns as jobs on a cluster? If you use multiple cores it will speed up significantly.

Honestly, if you cannot run it on a cluster I would perhaps suggest you use other software that are much faster and lighter (e.g. Whippet). 

M

**Comment by flolebill** [comment]
Here are the micX, exskx and IR2 files (in .txt) for one of the samples.

I'm not familiar with clusters, do you have any suggestion? I can use the "-c" option during the alignment.
To follow your suggestion, I'll see how to install and use the software Whippet, thank you.

Florian

[Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001 MICX.txt](https://github.com/vastgroup/vast-tools/files/4903730/Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001.MICX.txt)

[Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001 IR2.txt](https://github.com/vastgroup/vast-tools/files/4903728/Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001.IR2.txt)


[Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001 EXSKX.txt](https://github.com/vastgroup/vast-tools/files/4903727/Cummins_001-2_FLB_siControl_Veh_1_S1_L001_R1_001.EXSKX.txt)

**Comment by mirimia** [comment]
Thanks. Yes, these files seem OK (i.e. the mapping went well). So it's probably an issue with eej2.

For cluster submission, it will depend on the cluster. Normally you'll need to specify the number of cores (e.g. 8) and memory limit. Then you can submit align using -c 8. 

If you have access to a cluster, ask around how to use it. It's worth it! ;-)

M

**Comment by flolebill** [comment]
If it suits you, I'll send a screenshot of the current alignment after completion to see what happens with the eej2.

I'll see about the potential access a cluster.

Florian

**Comment by mirimia** [comment]
Yes, sure! Also, please check if the eej2 file is empty or not once is done.

**Comment by flolebill** [comment]
Hello Manuel,
Please find attached the screenshots for the commands after running vast-tools align.
I confirm that the related eej2 file is empty too.
Is it helpful to you? I'm not able to draw any conclusion based on these information.
Florian
![Screenshot from 2020-07-11 03-14-17](https://user-images.githubusercontent.com/39013928/87219029-fb90d280-c325-11ea-9f8a-b113ced455b8.png)
![Screenshot from 2020-07-11 03-14-31](https://user-images.githubusercontent.com/39013928/87219031-fc296900-c325-11ea-8389-52abceb41e68.png)

**Comment by mirimia** [comment]
Hello,

Yes, you can see the word **Killed** after the line "Mapping reads to the "splice site-based" ..."

This means the process was killed by the system. If you were running it on the main node of the cluster, this is expected. The main nodes normally have rules so users don't run jobs that are too demanding or otherwise they may affect other users. 

I believe the solution is simply to submit the align as a job with sufficient memory and time.

Best
Manu

**Comment by flolebill** [comment]
Hello Manuel,

Thank you very much for solving this problem.
I'll try to find a cluster to work on, or/and to enhance the memory and time dedicated to the use of vast-tools.

Best,
Florian
