### ISSUE TITLE
vast-tools diff failed and vast-tools compare_expr issue

### ISSUE THREAD

**Issue by flolebill** [vastgroup/vast-tools#92]
Dear Manuel Irimia and vast-tools team,

I am encountering other problems using vast-tools that I was not able to solve while reading previous issues on this website.

After having a problem with the combine tools, that I was able to solve thanks to Manuel, I have now a problem with the diff tool.
I have performed a set of alignment, merging and combining with the will to consider both AS and expression events.
When came the time to perform differential analysis, the terminal answered me that multiple warnings happened. Please see the screenshot below. I was not able to use "warning()" to see the first 50 of them.

![Screenshot Terminal_Diff with Expr data](https://user-images.githubusercontent.com/39013928/90586953-524fbe80-e1a6-11ea-8f3a-6fefcfb56731.png)
 
I have then tried to use the compare_expr tool. I had an error message indicating that "vast compare needs a cRPKM + COUNTs table". I did indicate the appropriate table on the command line, as you can see below.

![Screenshot Terminal_compare_expr attempts](https://user-images.githubusercontent.com/39013928/90587281-02252c00-e1a7-11ea-9679-04a73fe2ec17.png)

And the table itself is located on my "vast-out" directory, as you can see here:

![Screenshot Home - vast-tools - vast_out file](https://user-images.githubusercontent.com/39013928/90587350-297bf900-e1a7-11ea-8491-d359fb6ccb8a.png)

I've tried to run the compare_expr tool with the "--install_limma" option, unsuccessfully.
![Screenshot Terminal_compare_expr attempts with --install_limma option](https://user-images.githubusercontent.com/39013928/90587406-4dd7d580-e1a7-11ea-8c9d-ffa61f00d79d.png)

I can now provide you some screenshots to allow you to evaluate if the files resulting from the alignement, merging and combining are good. At least, they exist and have a size indicated.

![Screenshot Home - vast-tools file](https://user-images.githubusercontent.com/39013928/90587509-8ecfea00-e1a7-11ea-90f8-401e821aefd9.png)
![Screenshot vast_out - expr_out file](https://user-images.githubusercontent.com/39013928/90587516-95f6f800-e1a7-11ea-97d3-41f0195737b7.png)
![Screenshot vast_out - raw_incl file](https://user-images.githubusercontent.com/39013928/90587526-9c856f80-e1a7-11ea-921a-d5f06d42faad.png)
![Screenshot vast_out - raw_reads file](https://user-images.githubusercontent.com/39013928/90587538-a14a2380-e1a7-11ea-8713-33262936440e.png)
![Screenshot vast_out - to_combine file](https://user-images.githubusercontent.com/39013928/90587545-a4ddaa80-e1a7-11ea-8025-b8dfb1c207e7.png)
![Screenshot vast_out - to_combine with combined files name](https://user-images.githubusercontent.com/39013928/90587554-ab6c2200-e1a7-11ea-8b46-be48b93eaf35.png)

I hope that with these information, you will be able to understand my problem.
I will obviously provide any supplemental information that you would need.

Thank you in advance for your help,
Best regards,

Florian

**Comment by UBrau** [comment]
Hi Florian,
The issue with diff looks like diff is not being started correctly. It could be an installation issue. If you just type 
`vast-tools diff -h`
do you get the help text?

Ulrich

**Comment by mirimia** [comment]
Hello,

Regarding `compare_expr`, you're providing the cRPKM (only) table, not the cRPKM_AND_COUNTS table. To generate this, you need to use the -C option in combine. You can get it quickly (without doing the slow splicing part of combine) doing:

vast-tools combine --exprONLY -C -o ./FOLDER  -sp Species

Cheers
Manu

**Comment by flolebill** [comment]
> Hi Florian,
> The issue with diff looks like diff is not being started correctly. It could be an installation issue. If you just type
> `vast-tools diff -h`
> do you get the help text?
> 
> Ulrich

Hi Ulrich,
I do get the help text once I type vast-tools diff -h, as you can see on the following screenshots.
![Screenshot Terminal after diff -h 1](https://user-images.githubusercontent.com/39013928/90683295-4b6f8d00-e234-11ea-9488-8600384ca77c.png)
![Screenshot Terminal after diff -h 2](https://user-images.githubusercontent.com/39013928/90683299-4d395080-e234-11ea-9dce-e3ca5354921f.png)

Florian

**Comment by flolebill** [comment]
> Hello,
> 
> Regarding `compare_expr`, you're providing the cRPKM (only) table, not the cRPKM_AND_COUNTS table. To generate this, you need to use the -C option in combine. You can get it quickly (without doing the slow splicing part of combine) doing:
> 
> vast-tools combine --exprONLY -C -o ./FOLDER -sp Species
> 
> Cheers
> Manu

Hi Manuel,

Your solution did work very well. 
I'm surprised that there are only 4 GE events that differ in these samples but at least I can run the tool now. 
Thank you very much.

Florian

![Screenshot compare_expr Test 1](https://user-images.githubusercontent.com/39013928/90683466-95587300-e234-11ea-8b65-f993861eed0b.png)

**Comment by mirimia** [comment]
Great. Keep in mind, though, that vast-tools is not really designed for fine GE analysis. It's just meant to give you a sense of the potential changes. (However, if you only see 4 changes here, in my experience, it's unlikely you'll find many strong changes with other software either).

**Comment by sk1350** [comment]
Hello vast-tools team, 
Has the vast-tools diff issue described in this post been resolved? I see the same error message:
Trying to load required package: optparse
Trying to load required package: MASS
Trying to load required package: RColorBrewer
Trying to load required package: reshape2
Trying to load required package: ggplot2
Trying to load required package: grid
Trying to load required package: parallel
There were 50 or more warnings (use warnings() to see the first 50)

**Comment by mirimia** [comment]
Hello,

These might be just "harmless" warnings from the R analyses. Unfortunately, diff is beyond my knowledge, but perhaps @UBrau can confirm.

Thanks
Manu

**Comment by UBrau** [comment]
Hello sk1350,

Are you experiencing any actual errors (i.e., does diff not produce the 
expected output)? If so, please provide sample input. What you are 
showing looks harmless.

Ulrich

**Comment by sk1350** [comment]
Hello, 

It did turn out to be a harmless error as diff did provide output. However I now have a different question. 
I ran vast-tools compare and it shows 0 intron retention events even though all the other AS tools I've used showed IR for this dataset. Could there have been a mistake during align or combine? 

perl vast-tools compare vast_out/INCLUSION_LEVELS_FULL-xenTro3-5.tab -a stage10_1,stage10_1_1 -b stage14_1,stage14_1_1,stage15_1 --min_dPSI 10
[vast compare]: VAST-TOOLS v2.5.1
[vast compare]: Doing comparisons of AS profiles (stage10 vs stage14)
[vast compare]: Printing summary statistics

*** Options: dPSI=10, range_dif=5, min_ALT_use=25
*** Summary statistics:
	AS_TYPE	Higher_in_stage10	Higher_in_stage14	TOTAL_EV	TOTAL_AS(10<PSI<90)
	Microexons	11	4	632	42
	Long_AltEx	108	44	28212	514
	Intron_ret	0	0	0	0
	Alt_3ss	NA	0	0	0
	Alt_5ss	NA	0	0	0

**Comment by mirimia** [comment]
Hello,

Yes, it looks as if you have run combine with the --onlyEX option. (Judging from the number of total exons, though, the coverage of the RNA-seq is not very high, so you may want to consider merging the replicates).

M

**Comment by sk1350** [comment]
Hello, 

Thank you for the merging the replicates suggestion. This is an old dataset and the coverage is quite low.
I didn't see anything about the --onlyEX option in the combine part of documentation, is it standard or has to be specified? 

Sofia

**Comment by mirimia** [comment]
Hi Sofia,

It has to be specified, so it's strange then (it's explain in the help message of vast-tools combine). I recommend you pull the latest version of vast-tools and then run combine and compare again, just in case.

If you want, you can also do a ls -l to the to_combine/ folder, paste it here, and I'll see if the files look OK.

M

**Comment by mirimia** [comment]
Hi again,

Have you checked the information provided by vast-tools combine (in the standard output) when you ran it? It should have probably informed you about possible errors (i.e. that some tables were missing).

M

**Comment by sk1350** [comment]
Hello, 

Thank you for your suggestions. So I tried combining my files and checking I do not use the --onlyEX option but when I run 
vast-tools combine -sp Xt1 -o /mnt/lustre/users/sk1350/tropicalis/vast-tools/vast_out -IR_version 2 -extra_eej 5 

I get this error:

[vast combine error]: in call /mnt/lustre/users/sk1350/tropicalis/vast-tools/bin/RI_MakeTablePIR.R --verbose 1 -s /mnt/lustre/users/sk1350/tropicalis/vast-tools/VASTDB/Xt1 --IR_version 2 -c /mnt/lustre/users/sk1350/tropicalis/vast-tools/vast_out/to_combine -q /mnt/lustre/users/sk1350/tropicalis/vast-tools/vast_out/to_combine/Coverage_key_v2-Xt17.IRQ -o /mnt/lustre/users/sk1350/tropicalis/vast-tools/vast_out/raw_incl
/usr/bin/env: Rscript: No such file or directory

[vast combine]: Combining results into a single table
cat: raw_incl/INCLUSION_LEVELS_ALT3-Xt17-n.tab: No such file or directory
cat: raw_incl/INCLUSION_LEVELS_ALT5-Xt17-n.tab: No such file or directory
cat: raw_incl/INCLUSION_LEVELS_IR-Xt17.tab: No such file or directory

(The raw_incl folder is also missing the Xt14 and Xt15 versions of these files) 

The VTS_LOG_commands file shows that I use this command for alignment:
vast-tools align -sp Xt1 -o /mnt/lustre/users/sk1350/tropicalis/vast-tools/vast_out -c 35 -IR_version 2 -stepSize 25 -mismatchNum 2

**Comment by mirimia** [comment]
Hello Sofia,

I see. Two things: 

- could you please open a new Issue? This is no longer related to the topic of the issue. Thanks!
- silly question, but just in case: do you have R installed!? The error "/usr/bin/env: Rscript: No such file or directory" seems very R related to me...
