### ISSUE TITLE
Proxy error when downloading db

### ISSUE THREAD

**Issue by laurie-tonon** [vastgroup/vast-tools#95]
Hi,

I tried to download the VASTDB files to use vast-tools on my RNAseq data but the server seems to be down.
I encounter a proxy error every time I try to wget the folders or even with a browser.
Can you help me?
I can't use vast-tools as a result for the moment.

Thanks a lot

**Comment by mirimia** [comment]
Hello,

Thanks for letting us know. It seems the VastDB site is down altogether, so this should be restored very soon.

Thank you for your patience!
manu
