### ISSUE TITLE
Wrong Species Selected

### ISSUE THREAD

**Issue by juliana-chu** [vastgroup/vast-tools#96]
Hello there!
I ran into an error saying that "wrong species selected" on Scinet which needs access from terminal. I tried the same sample on my local terminal, it ran just fine. The sample I use is from specie araTha10.
this is the command I used on both terminal:
`vast-tools align D7K60W2_190919_NextSeq.fastq -sp araTha10 `
this is the error I received:
`[vast align]: Set tmp directory to /gpfs/fs0/scratch/n/nprovart/julianac/vast-ww60/tmp!
sh: bowtie: command not found
Too few first reads (<500) could be mapped to mRNA library for detecting strand-orientation of reads. Maybe wrong species selected? at /gpfs/fs1/home/n/nprovart/julianac/vast-tools/bin/RunDBS_1.pl line 599.`
 Also,  In the system they have bowtie 2.3.4.3, instead of bowtie 1.0. so I used 2, should I switch to bowtie 1.0?

**Comment by mirimia** [comment]
Hello,

Yes, I think this is an issue with bowtie, since it says no read has been mapped. Please use bowtie1 and let me know if that works.

thanks
Manu

**Comment by juliana-chu** [comment]
Hello,Manu

After I changed to bowtie 1, it worked! Thank you!
