### ISSUE TITLE
Error with psiplot

### ISSUE THREAD

**Issue by juliana-chu** [vastgroup/vast-tools#97]
Hello, there!
 
I have currently experiencing an error with PSI-Plot. When I command "vast-tools plot /vast_out/cRPKM-araTha10-1.tab", it returns with an error saying that I don't have psiplot. 
The Error is:
Trying to load required package: optparse
Trying to load required package: psiplot
Error: package or namespace load failed for ‘psiplot’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.5 is being loaded, but >= 0.4.7 is required
psiplot did not load correctly! Now trying to install..
Loading required package: psiplot
Error in loadPackages(c("psiplot", "methods", "labeling"), local.lib = paste(c(scriptPath,  : 
  quitting!!! I could not install psiplot for you!
In addition: Warning messages:
1: package ‘psiplot’ is not available (for R version 3.5.1) 
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘psiplot’
Execution halted

I wonder how can I download psiplot into my computer? I have used this command before, but it ran completely fine. I don't know what happened with this time. Please help me!
Thanks

**Comment by mirimia** [comment]
Hello!

It seems it's "just" an R package installation issue. Did you run it in the same computer before and it worked? Or was it in a different one?

I think the easiest is that you ask around for basic R help, since I have little idea about it. I think it should be easy to solve for someone with basic R knowledge, though. It seems to me that the automatic installation has probably changed for newer R versions, so it crashes. I'll also try to dig from my side. 

I'm CCing @kcha and @UBrau, but I'm not sure they'll have time to help any time soon...

Thanks
Manu

**Comment by kcha** [comment]
The error indicates that psiplot isn't installed. If it was working before, then perhaps check if you are using the same environment.

You can install psiplot using instructions here: https://github.com/kcha/psiplot#installation. Or perhaps better to run the provided install.R script in case you are missing any other dependencies.

Having said that, it looks like there is a bug in the vast-tools method that attempts to install missing R packages that are not hosted on CRAN. I don't have time to look at it now but easiest solution is to ensure that the prerequisites have been installed (manually or via install.R).

**Comment by mirimia** [comment]
Thanks a lot @kcha !

RE the bug: I think it's just that the vast-tools installer got obsolete for new R versions. That method worked for old versions. We'll try to fix it.

M

**Comment by juliana-chu** [comment]
Thanks to @kcha, I have reinstall the vast-tool again with install.R. This helped with the error!

Thanks

**Comment by juliana-chu** [comment]
Thanks for the advices! 

I have tried to reload the R packages, but it still returns errors. These are the errors I've got from Scient:
`Warning in install.packages(c("optparse", "RColorBrewer", "reshape2", "ggplot2",  :
  'lib = "/gpfs/fs1/scinet/niagara/software/2019b/opt/gcc-8.3.0/r/3.5.3/lib64/R/library"' is not writable
Error in install.packages(c("optparse", "RColorBrewer", "reshape2", "ggplot2",  : 
  unable to install packages`
`Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
`
And these are the errors I've got from my local terminal:
`> install.packages(c("optparse", "RColorBrewer", "reshape2", "ggplot2", "devtools"))
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> grep -> contrib.url
Execution halted`

Please tell me how to correct it.

Thanks,
Juliana

**Comment by kcha** [comment]
The first error seems like you don't have the correct permissions to install R packages on Scient. Should probably ask your admin.

The second error is saying that you need to set a mirror. `install.packages(..., repos='http://cran.us.r-project.org')`

Did using the `install.R` script not work?

**Comment by juliana-chu** [comment]
Hello, sorry for the late reply.

I used install.R but it still didn't work, but I have reload my R into version 3.5. Then it worked!

Thank you for all!
